### ISSUE TITLE
New families and individuals being created when importing by ID match (legacy IDs)

### ISSUE THREAD

**Issue by zarniwoop** [churchio/onebody#676] opened 2017-07-04 04:21 UTC
As a user importing data through CSV from PowerChurch;
I want OneBody not to create new families and individuals when I ask it to match by ID, I include legacy_id and legacy_family_id in the import, and there are already People and Families in the database that match to those legacy IDs;
So that I don't have to match by name in order to prevent duplicate records from being created.

(If I need to provide sample upload data for this, let me know)

**Comment by seven1m** [comment] 2017-07-05 03:52
@zarniwoop I'm surprised by this issue. This is exactly how it's _supposed_ to work ... maybe there is a bug here. I'll look into this...

**Comment by seven1m** [comment] 2017-08-01 05:24
@zarniwoop if you could provide a small sample file for me to test with, that would be helpful. Thanks!

**Comment by seven1m** [comment] 2017-08-19 20:42
I cannot reproduce this... closing until I get a sample file to test with.

**Closed by seven1m** 2017-08-19 20:42 UTC
Labels: bug
