### ISSUE TITLE
Inline images appear as attachments and render improperly

### ISSUE THREAD

**Issue by hooray4me** [churchio/onebody#608] opened 2016-05-02 23:33 UTC
What was composed:
![image](https://cloud.githubusercontent.com/assets/12399138/14971034/f6016f08-1093-11e6-9af6-ba2318bd93e2.png)

And what is received via email:
![image](https://cloud.githubusercontent.com/assets/12399138/14971053/1925691c-1094-11e6-9f8f-5e3c91584d14.png)

And what is rendered in onebody:
![image](https://cloud.githubusercontent.com/assets/12399138/14971078/4b22509c-1094-11e6-8373-d7e1327072b7.png)

**Comment by hooray4me** [comment] 2016-05-02 23:44
This is similar to issue #587

**Comment by seven1m** [comment] 2016-05-03 00:50
Duplicate of #587. I'm working on this 😄

**Closed by seven1m** 2016-05-03 00:50 UTC
